### ISSUE TITLE
Questions about the real experiments/set-up

### ISSUE THREAD

**Issue by Marcelbgit** [robot-learning-freiburg/CEILing#2]
Dear Eugenio,

it's me again with great progress and some open questions and I would be grateful if you could help me with my questions. 
Using the ROS interface "simExtROS" it is now possible for me to include the real camera stream of my Intel Realsense 435i into the simulation and to use teleoperation to control the robot (via the "action" content) in Coppeliasim and simultaneously in the real Kukarobot. With this I would like to record 10 real demonstrations as a data set like in the pure simulation, train them afterwards and have a real evaluation like your experiments. 

1. you have chosen the Intel Realsense IR300, which supports a minimum resolution of 320x180 P (like the 435i). However, 128x128 pixels are required as input. So do you reduce the resolution beforehand? In CoppeliaSim, the resolution of the vision sensors must match the resolution of the camera, otherwise the input image will be distorted. Also what happens when I increase the resolution in general? Does the performance increase for fine parts?
2. in the real demonstrations, how can I end the episode after capturing the real image-action pair, if I don't have any success condition at all like in the proximity sensor in the simulation. I have seen "Done" will be set from the env. Can I set done also for example with a keyboard key? Or what approach did you take for this? 
3. for clean shots and comparability of the real robot (or end effector position) with the simulation robot, I would like to prevent the lowering of the panda in the simulation, which happens over time. Do you have a tip for me here why this is done and how I can prevent it? 
4. as I described before, I control the real robot step by step with the information from "action". I have the question, if I need the actual robot joints of the real robot anywhere in the python files, or is it sufficient to bring the robots (or the end effector because of the different kinematics of the robots) in the same position in simulation and in reality. I hope you can follow me 
5. Last but not least, because of the path planning each single step, with which the real robot moves through the teleoperation, has a long duration (about 0.5 sec). Therefore I had the idea to write a function for the real teleoperation, with which one can increase or decrease the step size via key (0.9 mm, 9 mm and 90 mm). Here the question arises, how these step sizes would affect the training, if the robot moves abruptly by 90 mm. Does it make sense to you?

Sorry for the many questions and hopefully you can help me here.
Cheers,
Marcel

**Comment by chisarie** [comment]
HI marcel, to follow in order:

1. Yes I decreased the resolution because with smaller images training will be easier (less data needed, less time to train).
2. Yes in the real robot experiment I was setting done with a key press. In my case it was the "z" key.
3. I am not sure why this happens. Since it was not a big problem for me, I didn't dig into it. So I am not sure how to prevent it.
4. Mmm I think I cannot follow you.
5. I think you can do this. I didn't try it before, so I don't know how it will affect training

**Comment by Marcelbgit** [comment]
Hi Eugenio,

thanks for your reply. Also ask in order.
1. Alright. But it's still possible to use a higher resolution? In addition, would a higher resolution lead to a more sensitive behavior in the evaluation part and a longer calculation time of the policy? 
2. In the meantime I already wrote a similar function.
3. It looks like the target values for the joints (of coppeliasim) are overwritten constantly but neither changes in the config files nor in the task_design.ttt stop the constant lowering. Can you tell me what the purpose of "static_env": False and "headless_env": False is? I assumed that setting static_env True stop the lowering, but it doesn't. I don't understand why that wasn't a big problem for your real robot experiments. Because when it lowers the EE_Pose doesn't fit to the one of the EE_Pose of the simulation while recording demonstrations. This returns wrong endeffector position change in obs.joint_positions of EE_POSE_EE_FRAME sometime if the robots don't fit properly. Maybe it's a dumb question, sorry. You did use coppeliasim for the real experiments but with a API to the real robot?

In addition, I collected 10 test demonstrations with real images (wrote a lua script that crop my resolution from 320x180 (lowest resolution that is supported by realsense) to 128x128 pixel. But I am not sure if it really crop the images. These values as well as the sequenz_len were changed (from 150 to 650, because otherwise it quit coppeliasim). When I try to train the set, the resulting error is: 

`(ceiling_env) engine:~/CEILing$ python src/behavior_cloning.py --task PickUpReal --feedback_type pretraining
cuda:0
Traceback (most recent call last):
  File "src/behavior_cloning.py", line 71, in <module>
    main(config)
  File "src/behavior_cloning.py", line 35, in main
    train_step(policy, replay_memory, config)
  File "src/behavior_cloning.py", line 13, in train_step
    training_metrics = policy.update_params(
  File "/home/CEILing/src/models.py", line 65, in update_params
    loss = self.forward(camera_obs, proprio_obs, action, feedback)
  File "/home/CEILing/src/models.py", line 47, in forward
    mu, lstm_state = self.forward_step(
  File "/home/CEILing/src/models.py", line 38, in forward_step
    lstm_out, (h, c) = self.lstm(low_dim_input, lstm_state)
  File "/home/anaconda3/envs/ceiling_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/ceiling_env/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 579, in forward
    self.check_forward_args(input, hx, batch_sizes)
  File "/home/anaconda3/envs/ceiling_env/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 530, in check_forward_args
    self.check_input(input, batch_sizes)
  File "/home/anaconda3/envs/ceiling_env/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 178, in check_input
    raise RuntimeError(
RuntimeError: input.size(-1) must be equal to input_size. Expected 264, got 928`

Is it because of the changed sequence length? And when what do I have to change? Sorry for the many questions.

Maybe it is better to clarify your procedure for the real experiments in a 5 minute phone call to me, if you can give me five minutes of your time.

Thank you a lot for your help and your time,
Marcel

**Comment by Marcelbgit** [comment]
Hey Eugenio,

have you had a change to have a look on my prob? Thank you so far!

Cheers
Marcel

**Comment by chisarie** [comment]
Hi Marcel, 

I think this is the main misunderstanding. I do **not** use Coppeliasim nor RLBench in the real robot experiments. I only use the simulator for the simulation experiments. For the real robot, it is just my policy and the robot itself. No simulator, no visualization.

Regarding the error you get, it seems it has to do with the input size of your network, caused by the fact that you changed image resolution and sequence length. I cannot debug your code though, so I think you are on your own on this.
