### ISSUE TITLE
Error: QObject: Timers cannot be stopped from another thread

### ISSUE THREAD

**Issue by sung8331** [robot-learning-freiburg/CEILing#3]
Hello,
 
 I have run into a problem after taking 10 demonstrations of the robot closing the microwave door. After taking 10 demonstrations, I get the error: "Timers cannot be stopped from another thread". I am not able to move forward after that. I have attached some pictures from the error.
 
Do you know how I can resolve it?
 
I appreciate any help you would give me
 
Thank you

![15CF6CDB-1176-40A1-A896-8A5E7481DD1E](https://user-images.githubusercontent.com/96171779/158230508-f4ba4b38-175d-4124-9650-69d8d0cc7e02.jpeg)
![BD5487E0-8912-4376-857E-F276015E304D](https://user-images.githubusercontent.com/96171779/158230519-98cfbe31-077f-4614-987e-fd597b04f171.jpeg)

**Comment by chisarie** [comment]
Hi, what is exactly that you want to achieve? If you want to collect more demonstrations, simply set in `teleoperation_env.py` the config `"episodes": x,`, where x is the number of demonstrations you wish to collect. The error you see only happens when your script finishes and it is related to the simulator rather than to CEILing.

**Comment by sung8331** [comment]
> Hi, what is exactly that you want to achieve? If you want to collect more demonstrations, simply set in `teleoperation_env.py` the config `"episodes": x,`, where x is the number of demonstrations you wish to collect. The error you see only happens when your script finishes and it is related to the simulator rather than to CEILing.

Hello, For now, I am trying to replicate your training process. I am trying to move past the demonstrations. The error comes after taking 10 demonstrations hindering me from moving on to the next step of the training process

**Comment by chisarie** [comment]
Does the `demos_10.dat` get saved in the data folder after collection 10 demonstrations? If yes, then it means your demonstration collection succeeded and you can move to the next step, i.e. training a policy.

**Comment by sung8331** [comment]
> Does the `demos_10.dat` get saved in the data folder after collection 10 demonstrations? If yes, then it means your demonstration collection succeeded and you can move to the next step, i.e. training a policy.

Yes I can see the file now. Thank you
