### ISSUE TITLE
Key combinations 

### ISSUE THREAD

**Issue by Marcelbgit** [robot-learning-freiburg/CEILing#4]
Dear Eugenio,

just a question about the direction by pushing keys. Is it intended to push several buttons at the same time? For example Down+Left to move in two directions down and left. I have everything implemented and adjusted to my robot but pushing several buttons/directions only works for the half of it. In the provided clip you correcting the movement of the robot only in one direction. There is no record for collecting the demonstration.

Thanks for your help!
Best regards,
Marcel

**Comment by chisarie** [comment]
Pushing multiple keys at the same time should work. Are you using a joystick or the keyboard?

**Comment by Marcelbgit** [comment]
Hi Eugenio,

thanks for your fast reply and your help! The issue is, that only the half of the combinations with translational directions and up/down work (orientations with up/down are working perfectly). I couldn't figure out why. It's not about the robot, it's suppose to be about the script. Did you collect the demonstrations with just one key at once or did you use combinations? I use both keyboard and the same game pad as you. Do you have any ideas, what cause the problem?

thanks for your help,
Marcel

**Comment by chisarie** [comment]
I am able to do multiple keys at the same time. Maybe the robot is already at the joint limits, so it cannot move in that direction anymore? DId you try from a different position?

**Comment by Marcelbgit** [comment]
thanks for your response and suggestions.
And you train it pushing two directions at the same time, right? I already tested it in different joint (also in the middle of the range for the maximum joint positions +/-) but there are still some combinations like up and left/forward and down right/backwards that doesn't create a valid output or a move signal at all. Anyway the robot also moves kind of to the trained object also with one direction, but I will keep track of the problem.

Just two other things and hopefully you can help me out there:
-as mentioned earlier, I can successfully record a behavior cloning with 10 demonstrations and also apply/evaluate it with evalute.py. For this I chose 5 mm and 1.25 ° per step for translational and rotational movements in teleoperation/evaluate. When I apply the same for the feedback_train.py (now of course pretraining, which I also tried with 2000 steps -> no difference) the robot makes significantly smaller (almost towards 0 mm steps) despite default and I can't explain why. It's seems like it's because of the pretraining_policy (because it also return small values in evaluate with pretrain as well)  but I couldn't find other train parameters than "steps". Do you have a guess for this?

-the reason for the much larger steps than your original implementation is that I run the position/linear path planning through the KUKA iiwa action-server/move-client and it has very long calculation times for calculating/executing the goal pose. Since you use the same robot, I would like to know how you managed to shorten them so that the robot can directly implement the positions with 20 Hz.

cheers,
Marcel

**Comment by chisarie** [comment]
The steps I set in my code are the Maximum achievable. The train policy will then be able to output any value in the interval [-max, max], so it can also learn to output values close to zero.
In our Kuka we do not use any action server, we do not use moveit and we do not use ros for that matter. Everything is directly implemented on the low level, so it is a different setup.
