### ISSUE TITLE
Issue With Training a CEILing policy

### ISSUE THREAD

**Issue by sung8331** [robot-learning-freiburg/CEILing#5]
I have an issue while trying to train the CEILing policy. After successfully getting 10 demonstrations and seeing that they are saved as demos_10.dat, I then move on to train using the function:  
python src/feedback_train.py --task CloseMicrowave --feedback_type ceiling_full

However, Coppeliasim opens for a few seconds then shuts down giving me the error (also shown in the picture): 
"RuntimeError: Attempting to deserialize object on a CUDA device but torch.device.is_available is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU"

I have cuda 11.2 installed

Any idea how I can fix this error?
![A6B23B8F-7EAA-4F97-87FD-3CBBB15C208A_1_201_a](https://user-images.githubusercontent.com/96171779/160459213-27d2f1f4-10fe-4a69-8c80-842ded471f2b.jpeg)

**Comment by chisarie** [comment]
Hi, you need to change this line: https://github.com/robot-learning-freiburg/CEILing/blob/bdc0be882a8d9dccbed9212b7083ee289288f2b7/src/utils.py#L24 to 
```python
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
```

**Comment by sung8331** [comment]
Now I have this error: "NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current pyTorch installation. The current pyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75"

I see this error when i have 1.7.1 installed according to your instructions. This error occurs when I am trying to Train a CEILing policy after taking the demonstrations
<img width="615" alt="Screen Shot 2022-04-11 at 3 46 05 PM" src="https://user-images.githubusercontent.com/96171779/162829411-e07132f9-926e-4247-8111-58521a77d0c4.png">


Any idea how I can resolve this?

**Comment by chisarie** [comment]
Try a higher version of Pytorch, it seems your gpu is too new for 1.7.1
