### ISSUE TITLE
About training without pretrained model

### ISSUE THREAD

**Issue by weixiang-smart** [robot-learning-freiburg/CEILing#7]
Dear Eugenio,

I think CEILing is a nice work in imitation learning！

I noticed that your training code needs to read the pretrained weights. Is it possible to train the new model without your pretrained model? 

Looking forward to your reply!

Best regards,
Xiang

**Comment by chisarie** [comment]
Hello!
Yes it is definitely possible, you just need to remove these two lines from the main training script: 

https://github.com/robot-learning-freiburg/CEILing/blob/bdc0be882a8d9dccbed9212b7083ee289288f2b7/src/feedback_train.py#L60-L61

**Comment by weixiang-smart** [comment]
> Hello! Yes it is definitely possible, you just need to remove these two lines from the main training script:
> 
> https://github.com/robot-learning-freiburg/CEILing/blob/bdc0be882a8d9dccbed9212b7083ee289288f2b7/src/feedback_train.py#L60-L61
Thank you so much for your help!

**Comment by weixiang-smart** [comment]
Thank you so much for your help! @chisarie
